
/*
 * This file is generated by jOOQ.
 */
package org.seqra.ir.impl.storage.ers.jooq


import kotlin.collections.List

import org.seqra.ir.impl.storage.ers.jooq.tables.Types
import org.jooq.Catalog
import org.jooq.Table
import org.jooq.impl.SchemaImpl


/**
 * This class is generated by jOOQ.
 */
@Suppress("UNCHECKED_CAST")
open class DefaultSchema : SchemaImpl("", DefaultCatalog.DEFAULT_CATALOG) {
    companion object {

        /**
         * The reference instance of <code>DEFAULT_SCHEMA</code>
         */
        val DEFAULT_SCHEMA = DefaultSchema()
    }

    /**
     * The table <code>Types</code>.
     */
    val TYPES get() = Types.TYPES

    override fun getCatalog(): Catalog = DefaultCatalog.DEFAULT_CATALOG

    override fun getTables(): List<Table<*>> = listOf(
        Types.TYPES
    )
}
