
/*
 * This file is generated by jOOQ.
 */
package org.seqra.ir.impl.storage.ers.jooq.tables.records


import org.seqra.ir.impl.storage.ers.jooq.tables.Types
import org.jooq.Field
import org.jooq.Record1
import org.jooq.Record2
import org.jooq.Row2
import org.jooq.impl.UpdatableRecordImpl


/**
 * This class is generated by jOOQ.
 */
@Suppress("UNCHECKED_CAST")
open class TypesRecord() : UpdatableRecordImpl<TypesRecord>(Types.TYPES), Record2<Int?, String?> {

    var id: Int?
        set(value) = set(0, value)
        get() = get(0) as Int?

    var name: String?
        set(value) = set(1, value)
        get() = get(1) as String?

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    override fun key(): Record1<Int?> = super.key() as Record1<Int?>

    // -------------------------------------------------------------------------
    // Record2 type implementation
    // -------------------------------------------------------------------------

    override fun fieldsRow(): Row2<Int?, String?> = super.fieldsRow() as Row2<Int?, String?>
    override fun valuesRow(): Row2<Int?, String?> = super.valuesRow() as Row2<Int?, String?>
    override fun field1(): Field<Int?> = Types.TYPES.ID
    override fun field2(): Field<String?> = Types.TYPES.NAME
    override fun component1(): Int? = id
    override fun component2(): String? = name
    override fun value1(): Int? = id
    override fun value2(): String? = name

    override fun value1(value: Int?): TypesRecord {
        this.id = value
        return this
    }

    override fun value2(value: String?): TypesRecord {
        this.name = value
        return this
    }

    override fun values(value1: Int?, value2: String?): TypesRecord {
        this.value1(value1)
        this.value2(value2)
        return this
    }

    /**
     * Create a detached, initialised TypesRecord
     */
    constructor(id: Int? = null, name: String? = null): this() {
        this.id = id
        this.name = name
    }
}
