
/*
 * This file is generated by jOOQ.
 */
package org.seqra.ir.impl.storage.ers.jooq.tables.references


import org.seqra.ir.impl.storage.ers.jooq.tables.Types



/**
 * The table <code>Types</code>.
 */
val TYPES = Types.TYPES
