
/*
 * This file is generated by jOOQ.
 */
package org.seqra.ir.impl.storage.ers.jooq.keys


import org.seqra.ir.impl.storage.ers.jooq.tables.Types
import org.seqra.ir.impl.storage.ers.jooq.tables.records.TypesRecord
import org.jooq.UniqueKey
import org.jooq.impl.DSL
import org.jooq.impl.Internal



// -------------------------------------------------------------------------
// UNIQUE and PRIMARY KEY definitions
// -------------------------------------------------------------------------

val PK_TYPES: UniqueKey<TypesRecord> = Internal.createUniqueKey(Types.TYPES, DSL.name("pk_Types"), arrayOf(Types.TYPES.ID), true)
