
/*
 * This file is generated by jOOQ.
 */
package org.seqra.ir.impl.storage.jooq.tables.references


import org.seqra.ir.impl.storage.jooq.tables.*


/**
 * The table <code>Annotations</code>.
 */
val ANNOTATIONS = Annotations.ANNOTATIONS

/**
 * The table <code>AnnotationValues</code>.
 */
val ANNOTATIONVALUES = Annotationvalues.ANNOTATIONVALUES

/**
 * The table <code>ApplicationMetadata</code>.
 */
val APPLICATIONMETADATA = Applicationmetadata.APPLICATIONMETADATA

/**
 * The table <code>Builders</code>.
 */
val BUILDERS = Builders.BUILDERS

/**
 * The table <code>BytecodeLocations</code>.
 */
val BYTECODELOCATIONS = Bytecodelocations.BYTECODELOCATIONS

/**
 * The table <code>Calls</code>.
 */
val CALLS = Calls.CALLS

/**
 * The table <code>Classes</code>.
 */
val CLASSES = Classes.CLASSES

/**
 * The table <code>ClassHierarchies</code>.
 */
val CLASSHIERARCHIES = Classhierarchies.CLASSHIERARCHIES

/**
 * The table <code>ClassInnerClasses</code>.
 */
val CLASSINNERCLASSES = Classinnerclasses.CLASSINNERCLASSES

/**
 * The table <code>Fields</code>.
 */
val FIELDS = Fields.FIELDS

/**
 * The table <code>MethodParameters</code>.
 */
val METHODPARAMETERS = Methodparameters.METHODPARAMETERS

/**
 * The table <code>Methods</code>.
 */
val METHODS = Methods.METHODS

/**
 * The table <code>OuterClasses</code>.
 */
val OUTERCLASSES = Outerclasses.OUTERCLASSES

/**
 * The table <code>Refactorings</code>.
 */
val REFACTORINGS = Refactorings.REFACTORINGS

/**
 * The table <code>Symbols</code>.
 */
val SYMBOLS = Symbols.SYMBOLS
