
/*
 * This file is generated by jOOQ.
 */
package org.seqra.ir.impl.storage.jooq


import org.seqra.ir.impl.storage.jooq.tables.*
import org.jooq.Catalog
import org.jooq.Table
import org.jooq.impl.SchemaImpl


/**
 * This class is generated by jOOQ.
 */
@Suppress("UNCHECKED_CAST")
open class DefaultSchema : SchemaImpl("", DefaultCatalog.DEFAULT_CATALOG) {
    companion object {

        /**
         * The reference instance of <code>DEFAULT_SCHEMA</code>
         */
        val DEFAULT_SCHEMA = DefaultSchema()
    }

    /**
     * The table <code>Annotations</code>.
     */
    val ANNOTATIONS get() = Annotations.ANNOTATIONS

    /**
     * The table <code>AnnotationValues</code>.
     */
    val ANNOTATIONVALUES get() = Annotationvalues.ANNOTATIONVALUES

    /**
     * The table <code>ApplicationMetadata</code>.
     */
    val APPLICATIONMETADATA get() = Applicationmetadata.APPLICATIONMETADATA

    /**
     * The table <code>Builders</code>.
     */
    val BUILDERS get() = Builders.BUILDERS

    /**
     * The table <code>BytecodeLocations</code>.
     */
    val BYTECODELOCATIONS get() = Bytecodelocations.BYTECODELOCATIONS

    /**
     * The table <code>Calls</code>.
     */
    val CALLS get() = Calls.CALLS

    /**
     * The table <code>Classes</code>.
     */
    val CLASSES get() = Classes.CLASSES

    /**
     * The table <code>ClassHierarchies</code>.
     */
    val CLASSHIERARCHIES get() = Classhierarchies.CLASSHIERARCHIES

    /**
     * The table <code>ClassInnerClasses</code>.
     */
    val CLASSINNERCLASSES get() = Classinnerclasses.CLASSINNERCLASSES

    /**
     * The table <code>Fields</code>.
     */
    val FIELDS get() = Fields.FIELDS

    /**
     * The table <code>MethodParameters</code>.
     */
    val METHODPARAMETERS get() = Methodparameters.METHODPARAMETERS

    /**
     * The table <code>Methods</code>.
     */
    val METHODS get() = Methods.METHODS

    /**
     * The table <code>OuterClasses</code>.
     */
    val OUTERCLASSES get() = Outerclasses.OUTERCLASSES

    /**
     * The table <code>Refactorings</code>.
     */
    val REFACTORINGS get() = Refactorings.REFACTORINGS

    /**
     * The table <code>Symbols</code>.
     */
    val SYMBOLS get() = Symbols.SYMBOLS

    override fun getCatalog(): Catalog = DefaultCatalog.DEFAULT_CATALOG

    override fun getTables(): List<Table<*>> = listOf(
        Annotations.ANNOTATIONS,
        Annotationvalues.ANNOTATIONVALUES,
        Applicationmetadata.APPLICATIONMETADATA,
        Builders.BUILDERS,
        Bytecodelocations.BYTECODELOCATIONS,
        Calls.CALLS,
        Classes.CLASSES,
        Classhierarchies.CLASSHIERARCHIES,
        Classinnerclasses.CLASSINNERCLASSES,
        Fields.FIELDS,
        Methodparameters.METHODPARAMETERS,
        Methods.METHODS,
        Outerclasses.OUTERCLASSES,
        Refactorings.REFACTORINGS,
        Symbols.SYMBOLS
    )
}
