
/*
 * This file is generated by jOOQ.
 */
package org.seqra.ir.impl.storage.jooq.tables.records


import org.seqra.ir.impl.storage.jooq.tables.Applicationmetadata
import org.jooq.Field
import org.jooq.Record1
import org.jooq.Row1
import org.jooq.impl.TableRecordImpl


/**
 * This class is generated by jOOQ.
 */
@Suppress("UNCHECKED_CAST")
open class ApplicationmetadataRecord() : TableRecordImpl<ApplicationmetadataRecord>(Applicationmetadata.APPLICATIONMETADATA), Record1<String?> {

    var version: String?
        set(value) = set(0, value)
        get() = get(0) as String?

    // -------------------------------------------------------------------------
    // Record1 type implementation
    // -------------------------------------------------------------------------

    override fun fieldsRow(): Row1<String?> = super.fieldsRow() as Row1<String?>
    override fun valuesRow(): Row1<String?> = super.valuesRow() as Row1<String?>
    override fun field1(): Field<String?> = Applicationmetadata.APPLICATIONMETADATA.VERSION
    override fun component1(): String? = version
    override fun value1(): String? = version

    override fun value1(value: String?): ApplicationmetadataRecord {
        this.version = value
        return this
    }

    override fun values(value1: String?): ApplicationmetadataRecord {
        this.value1(value1)
        return this
    }

    /**
     * Create a detached, initialised ApplicationmetadataRecord
     */
    constructor(version: String? = null): this() {
        this.version = version
    }
}
